import { expect,test } from "bun:test";
import { parseArgs } from "../src/args.ts";
import { commandRequest } from "../src/commands.ts";
test("create preserves its JSON body after option parsing",()=>{const args=parseArgs(["projects","create",'{"name":"review"}',"--json"]);expect(commandRequest(args).body).toEqual({name:"review"});});
test("important workflows map to dedicated API operations",()=>{
 expect(commandRequest(parseArgs(["dispatch","submit","d-1"])).path).toBe("/api/dispatch/d-1/submit");
 expect(commandRequest(parseArgs(["approvals","decision","a-1","--approved","false","--reason","revise"])).body).toEqual({approved:false,reason:"revise"});
 expect(commandRequest(parseArgs(["tasks","action","t-1","--action","report","--progress","40"])).body).toEqual({action:"report",progress:"40"});
 expect(commandRequest(parseArgs(["reports","export","files","--from","2026-01-01","--out","files.json"])).download).toBe("files.json");
 expect(commandRequest(parseArgs(["people","load","u-1","--date=2026-06-01"])).path).toBe("/api/load/u-1?date=2026-06-01");
 expect(commandRequest(parseArgs(["admin","audit"])).path).toBe("/api/admin/audit");
 expect(commandRequest(parseArgs(["seed","status"])).path).toBe("/api/seed/status");
 expect(commandRequest(parseArgs(["projects","action","p-1","--action","pause","--reason","scope change"])).path).toBe("/api/projects/p-1/action");
 expect(commandRequest(parseArgs(["admin","delegations","u-1","--org-ids","o-1,o-2","--reason","coverage"])).body).toEqual({org_ids:["o-1","o-2"],reason:"coverage"});
 expect(commandRequest(parseArgs(["tasks","assign","t-1","--user-id","u-2","--start-date","2026-06-01","--end-date","2026-06-03","--daily-hours","4","--deliverables","overall-report,dataset"])).body).toEqual({user_id:"u-2",start_date:"2026-06-01",end_date:"2026-06-03",daily_hours:4,all_day:false,deliverables:["overall-report","dataset"]});
 expect(commandRequest(parseArgs(["task-assignments","requirements","a-1","--deliverables","overall-report,dataset"])).body).toEqual({action:"set_deliverables",deliverables:["overall-report","dataset"]});
 expect(()=>commandRequest(parseArgs(["task-assignments","requirements","a-1"]))).toThrow("requires ID and --deliverables CSV");
 expect(()=>commandRequest(parseArgs(["task-assignments","requirements","a-1","--deliverables"]))).toThrow("requires a CSV value");
 expect(commandRequest(parseArgs(["task-assignments","requirements","a-1","--deliverables="])).body).toEqual({action:"set_deliverables",deliverables:[]});
 expect(commandRequest(parseArgs(["task-assignments","action","a-1","--action","submit","--result","done"])).path).toBe("/api/task_assignments/a-1/action");
 expect(commandRequest(parseArgs(["files","rollback","f-1","--version-id","f-0","--reason","restore"])).body).toEqual({version_id:"f-0",reason:"restore"});
 expect(commandRequest(parseArgs(["tasks","assignments","t-1"])).path).toBe("/api/tasks/t-1/assignments");
 expect(commandRequest(parseArgs(["task-assignments","list"])).path).toBe("/api/task_assignments");
 expect(commandRequest(parseArgs(["task-assignments","show","a-1"])).path).toBe("/api/task_assignments/a-1");
 expect(commandRequest(parseArgs(["task-assignments","update","a-1","--start-date","2026-06-02","--end-date","2026-06-02","--daily-hours","6"])).body).toEqual({action:"reschedule",start_date:"2026-06-02",end_date:"2026-06-02",daily_hours:6,all_day:false});
 expect(commandRequest(parseArgs(["visibility_grants","create",'{"project_id":"p-1","user_id":"u-1","actions":["view"]}'])).path).toBe("/api/visibility_grants");
 expect(commandRequest(parseArgs(["visibility-grants","revoke","g-1"])).path).toBe("/api/visibility_grants/g-1/revoke");
 expect(commandRequest(parseArgs(["task-assignments","action","a-1","--action","submit","--result","done","--file-ids","f-1,f-2"])).body).toEqual({action:"submit",result:"done",reason:"",file_ids:["f-1","f-2"]});
 expect(commandRequest(parseArgs(["visibility-grants","list"])).path).toBe("/api/visibility_grants");
});
test("missing command arguments fail before network calls",()=>{expect(()=>commandRequest(parseArgs(["projects","create","{bad}"]))).toThrow("expected a JSON object");expect(()=>commandRequest(parseArgs(["dispatch","submit"]))).toThrow("requires dispatch ID");expect(()=>commandRequest(parseArgs(["tasks","assign","t-1","--user-id","u-2"]))).toThrow("requires ID");});
