import { z } from "zod";
import { sql } from "./db.ts";
import { canReadRecord, canWriteRecord, type User } from "./permissions.ts";
export const collections=["orgs","people","projects","tasks","dispatch","approvals","load","conflicts","files","inbox","tools","reports","config","admin","mentions","milestones","worklogs","visibility_grants","seed","invitations","registrations","config_versions"] as const;
export type Collection=typeof collections[number];
const uuid=()=>crypto.randomUUID();
const types=["research-company","research-department","research-center","market","business-trip","clerical","party","learning","leave"];
const schemas:Partial<Record<Collection,z.ZodTypeAny>>={
 orgs:z.object({name:z.string().min(1).max(128),type:z.enum(["company","second_level","center","department","studio"]),parent_id:z.string().nullable().optional(),enabled:z.boolean().default(true)}).passthrough(),
 people:z.object({name:z.string().min(1).max(128),org_id:z.string().min(1),title:z.string().optional(),status:z.enum(["active","leave","travel","unavailable","disabled"]).default("active"),daily_standard_hours:z.number().min(0).max(24).default(8),skills:z.array(z.string()).default([])}).passthrough(),
 projects:z.object({name:z.string().min(1).max(200),owner_id:z.string().min(1),org_id:z.string().min(1),visibility:z.enum(["normal","hidden","restricted"]).default("normal"),status:z.enum(["planning","active","paused","completed","archived"]).default("planning"),member_ids:z.array(z.string()).default([])}).passthrough(),
 tasks:z.object({name:z.string().min(1).max(240),type:z.string().refine(x=>types.includes(x)),owner_id:z.string().min(1),start_date:z.string().date(),end_date:z.string().date(),daily_hours:z.number().min(0).max(24),status:z.enum(["draft","pending_coordination","pending_confirmation","in_progress","pending_acceptance","done","archived","cancelled"]).default("draft"),member_ids:z.array(z.string()).default([]),project_id:z.string().optional()}).passthrough(),
 dispatch:z.object({task_id:z.string().min(1),requester_id:z.string().min(1),workflow:z.enum(["standard","supplemental"]),status:z.enum(["draft","pending_founder_confirmation","pending_approval","approved","rejected","published"]).default("draft"),target_org_ids:z.array(z.string()).default([])}).passthrough(),
 approvals:z.object({dispatch_id:z.string().min(1),step:z.enum(["department_director","center_director","founder_confirmation"]),approver_id:z.string().min(1),status:z.enum(["pending","approved","rejected"]).default("pending")}).passthrough(),
 files:z.object({name:z.string().min(1).max(255),category:z.enum(["personal-report","overall-report","presentation","application-report","dataset","minutes"]),object_key:z.string().min(1),content_type:z.string().optional(),size_bytes:z.number().int().nonnegative(),project_id:z.string().optional(),task_id:z.string().optional(),status:z.enum(["active","archived","deleted"]).default("active")}).passthrough(),
 visibility_grants:z.object({project_id:z.string().min(1),user_id:z.string().min(1),actions:z.array(z.enum(["view","edit"])).min(1),expires_at:z.string().datetime().optional()}).passthrough(),
};
function db(){if(!sql)throw new Error("DATABASE_URL required");return sql;}
export async function listRecords(user:User,kind:Collection):Promise<Array<Record<string,any>>> {
 const rows=await db()`SELECT id,tenant_id,created_by,data,created_at,updated_at FROM nexusflow.records WHERE kind=${kind} AND (${user.role==='super_admin'} OR tenant_id=${user.tenant_id} OR (tenant_id IS NULL AND created_by=${user.id})) ORDER BY created_at DESC`;
 const visible=[];for(const r of rows){const row={id:r.id,tenant_id:r.tenant_id,created_by:r.created_by,data:r.data as Record<string,unknown>};if(await canReadRecord(user,kind,row)){const data={...row.data};if(kind==="invitations")delete data.token_hash;visible.push({...data,id:r.id,created_at:r.created_at,updated_at:r.updated_at});}}return visible;
}
export async function getRecord(user:User,kind:Collection,id:string):Promise<Record<string,any>|null> {
 const rows=await db()`SELECT id,tenant_id,created_by,data,created_at,updated_at FROM nexusflow.records WHERE id=${id} AND kind=${kind} AND (${user.role==='super_admin'} OR tenant_id=${user.tenant_id} OR (tenant_id IS NULL AND created_by=${user.id}))`;const r=rows[0];if(!r)return null;
 const row={id:r.id,tenant_id:r.tenant_id,created_by:r.created_by,data:r.data as Record<string,unknown>};if(!await canReadRecord(user,kind,row))return null;const data={...row.data};if(kind==="invitations")delete data.token_hash;return {...data,id:r.id,created_at:r.created_at,updated_at:r.updated_at};
}
export async function createRecord(user:User,kind:Collection,input:Record<string,unknown>) {
 if("id" in input||"created_at" in input||"updated_at" in input)throw new Error("server-managed fields cannot be supplied");
 const parsed=schemas[kind]?.safeParse(input);if(parsed&&!parsed.success)throw new Error(parsed.error.issues.map(x=>`${x.path.join(".")}: ${x.message}`).join("; "));
 const data={...(parsed?.data||input)} as Record<string,unknown>;if(data.org_id&&user.org_id&&!['center_director','super_admin'].includes(user.role)&&data.org_id!==user.org_id)throw new Error("cross-department write forbidden");
 if(kind==="tasks"&&data.project_id){const project=await getRecord(user,"projects",String(data.project_id));if(!project)throw new Error("project unavailable");if(data.org_id&&data.org_id!==project.org_id)throw new Error("task organization must match project");}
 if(kind==="dispatch"){const task=await getRecord(user,"tasks",String(data.task_id));if(!task)throw new Error("task unavailable");if(data.requester_id!==user.id)throw new Error("dispatch requester must be the current user");if(Array.isArray(data.target_org_ids))data.target_org_ids=[...new Set(data.target_org_ids.map(String))];}
 if(kind==="visibility_grants"){const project=await getRecord(user,"projects",String(data.project_id));if(!project)throw new Error("project unavailable");if(!sql)throw new Error("DATABASE_URL required");const target=await sql`SELECT id FROM nexusflow.users WHERE id=${String(data.user_id)} AND tenant_id IS NOT DISTINCT FROM ${user.tenant_id} AND status='active'`;if(!target.length)throw new Error("grant target user unavailable");if(user.org_id&&project.org_id!==user.org_id&&!['center_director','super_admin'].includes(user.role))throw new Error("cross-department grant forbidden");data.org_id=project.org_id;}
 const row={tenant_id:user.tenant_id,created_by:user.id,data};if(!await canWriteRecord(user,kind,row,"create"))throw new Error("forbidden");
 if(kind==="approvals"||kind==="inbox"||kind==="conflicts"||kind==="worklogs"||kind==="load"||kind==="seed"||kind==="config_versions"||kind==="mentions")throw new Error("records of this type are created by domain actions");
 if(kind==="orgs"&&!['super_admin','center_director'].includes(user.role))throw new Error("organization management permission required");
 const id=uuid();await db().begin(async tx=>{await tx`INSERT INTO nexusflow.records(id,kind,tenant_id,created_by,data) VALUES(${id},${kind},${user.tenant_id},${user.id},${tx.json(data as any)})`;await tx`INSERT INTO nexusflow.audit(id,actor,tenant_id,action,object_kind,object_id,data) VALUES(${uuid()},${user.id},${user.tenant_id},${kind}.create,${kind},${id},${tx.json(data as any)})`;});return getRecord(user,kind,id);
}
export async function updateRecord(user:User,kind:Collection,id:string,patch:Record<string,unknown>) {
 if("id" in patch||"created_at" in patch||"updated_at" in patch||"created_by" in patch||"tenant_id" in patch)throw new Error("server-managed fields cannot be changed");
 if(kind==="tasks"&&["status","owner_id","member_ids","project_id","org_id","start_date","end_date","daily_hours","all_day"].some(k=>k in patch))throw new Error("use a task workflow action to change lifecycle or assignment");
 if(kind==="config"&&"status" in patch)throw new Error("use config publish action to change activation state");
 if(kind==="dispatch"&&"status" in patch||kind==="approvals"&&["status","approver_id","step"].some(k=>k in patch))throw new Error("use a dispatch or approval action to change workflow state");
 if(kind==="files"&&["status","object_key","size_bytes"].some(k=>k in patch))throw new Error("use the file archive or upload action");
 if(kind==="projects"&&["visibility","status","member_ids","owner_id"].some(k=>k in patch)&&!['super_admin','center_director','center_deputy','department_director'].includes(user.role))throw new Error("project administration permission required");
 const current=await getRaw(kind,id,user);if(!current)return null;if(!await canWriteRecord(user,kind,current,"update"))throw new Error("forbidden");
 const next={...current.data,...patch};const parsed=schemas[kind]?.safeParse(next);if(parsed&&!parsed.success)throw new Error(parsed.error.issues.map(x=>x.message).join("; "));
 await db().begin(async tx=>{await tx`UPDATE nexusflow.records SET data=${tx.json(next as any)},updated_at=now() WHERE id=${id} AND kind=${kind} AND tenant_id IS NOT DISTINCT FROM ${current.tenant_id}`;await tx`INSERT INTO nexusflow.audit(id,actor,tenant_id,action,object_kind,object_id,data) VALUES(${uuid()},${user.id},${user.tenant_id},${kind}.update,${kind},${id},${tx.json({before:current.data,after:next} as any)})`;});return getRecord(user,kind,id);
}
async function getRaw(kind:Collection,id:string,user:User){const r=(await db()`SELECT id,tenant_id,created_by,data FROM nexusflow.records WHERE id=${id} AND kind=${kind} AND (${user.role==='super_admin'} OR tenant_id=${user.tenant_id} OR (tenant_id IS NULL AND created_by=${user.id}))`)[0];return r?{id:r.id,tenant_id:r.tenant_id,created_by:r.created_by,data:r.data as Record<string,unknown>}:null;}
export async function deleteRecord(user:User,kind:Collection,id:string){if(kind==="files")return false;const r=await getRaw(kind,id,user);if(!r||!await canWriteRecord(user,kind,r,"delete"))return false;await db().begin(async tx=>{await tx`DELETE FROM nexusflow.records WHERE id=${id} AND kind=${kind}`;await tx`INSERT INTO nexusflow.audit(id,actor,tenant_id,action,object_kind,object_id,data) VALUES(${uuid()},${user.id},${user.tenant_id},${kind}.delete,${kind},${id},${tx.json(r.data as any)})`;});return true;}
export async function insertRecord(tx:any,user:User,kind:Collection,data:Record<string,unknown>) {const id=uuid();await tx`INSERT INTO nexusflow.records(id,kind,tenant_id,created_by,data) VALUES(${id},${kind},${user.tenant_id},${user.id},${tx.json(data)})`;return id;}
