import { z } from "zod";
import { sql } from "./db.ts";
import { canEditTask, canManage, canProjectAction, canReadRecord, canWriteRecord, type User } from "./permissions.ts";
import { validDate } from "./load.ts";
export const collections=["orgs","people","projects","tasks","dispatch","approvals","load","conflicts","files","inbox","tools","reports","config","admin","mentions","milestones","worklogs","visibility_grants","seed","invitations","registrations","config_versions","task_assignments"] as const;
export type Collection=typeof collections[number];
const uuid=()=>crypto.randomUUID();
const types=["research-company","research-department","research-center","market","business-trip","clerical","party","learning","leave"];
const schemas:Partial<Record<Collection,z.ZodTypeAny>>={
 orgs:z.object({name:z.string().min(1).max(128),type:z.enum(["company","second_level","center","department","studio"]),parent_id:z.string().nullable().optional(),enabled:z.boolean().default(true)}).passthrough(),
 people:z.object({name:z.string().min(1).max(128),org_id:z.string().min(1),title:z.string().optional(),status:z.enum(["active","leave","travel","unavailable","disabled"]).default("active"),daily_standard_hours:z.number().min(0).max(24).default(8),skills:z.array(z.string()).default([])}).passthrough(),
 projects:z.object({name:z.string().min(1).max(200),owner_id:z.string().min(1),org_id:z.string().min(1),visibility:z.enum(["normal","hidden","restricted"]).default("normal"),status:z.literal("planning").default("planning"),member_ids:z.array(z.string()).default([])}).passthrough(),
 tasks:z.object({name:z.string().min(1).max(240),type:z.string().min(1).max(64),owner_id:z.string().min(1),org_id:z.string().optional(),start_date:z.string().date(),end_date:z.string().date(),daily_hours:z.number().min(0).max(24),status:z.literal("draft").default("draft"),all_day:z.boolean().default(false),member_ids:z.array(z.string()).default([]),project_id:z.string().optional()}).passthrough(),
 dispatch:z.object({task_id:z.string().min(1),requester_id:z.string().min(1),workflow:z.enum(["standard","supplemental"]),status:z.literal("draft").default("draft"),target_org_ids:z.array(z.string()).default([])}).passthrough(),
 approvals:z.object({dispatch_id:z.string().min(1),step:z.enum(["department_director","center_director","founder_confirmation"]),approver_id:z.string().min(1),status:z.enum(["pending","approved","rejected","cancelled"]).default("pending")}).passthrough(),
 files:z.object({name:z.string().min(1).max(255),category:z.enum(["personal-report","overall-report","presentation","application-report","dataset","minutes"]),object_key:z.string().min(1),content_type:z.string().optional(),size_bytes:z.number().int().nonnegative(),project_id:z.string().optional(),task_id:z.string().optional(),status:z.enum(["active","archived","deleted"]).default("active")}).passthrough(),
 visibility_grants:z.object({project_id:z.string().min(1),user_id:z.string().min(1),actions:z.array(z.enum(["view","edit"])).min(1),expires_at:z.string().datetime().optional()}).passthrough(),
 config:z.object({key:z.literal("task_types"),value:z.object({types:z.array(z.string().regex(/^[a-z0-9-]{2,64}$/)).min(1).max(40)}),status:z.enum(["draft","published","superseded"]).default("draft"),version:z.number().int().nonnegative().default(0)}).passthrough(),
 task_assignments:z.object({task_id:z.string().min(1),user_id:z.string().min(1),start_date:z.string().date(),end_date:z.string().date(),daily_hours:z.number().min(0).max(24),all_day:z.boolean().default(false),status:z.enum(["assigned","pending_confirmation","active","pending_acceptance","accepted","rejected","cancelled"]).default("assigned"),progress:z.number().min(0).max(100).default(0),deliverables:z.array(z.string()).default([])}).passthrough(),
};
function db(){if(!sql)throw new Error("DATABASE_URL required");return sql;}
async function allowedTaskTypes(user:User){const rows=await db()`SELECT data FROM nexusflow.records WHERE kind='config' AND tenant_id IS NOT DISTINCT FROM ${user.tenant_id} AND data->>'key'='task_types' AND data->>'status'='published' ORDER BY updated_at DESC LIMIT 1`;const value=(rows[0]?.data as any)?.value?.types;return Array.isArray(value)&&value.every((x:any)=>typeof x==='string')?value:types;}
async function orgExists(user:User,id:string){return Boolean(await getRecord(user,"orgs",id));}
async function orgDescendant(user:User,child:string,parent:string){if(child===parent)return true;const orgs=await listRecords(user,"orgs"),parents=new Map(orgs.map(o=>[String(o.id),String(o.parent_id||"")]));let current=child;for(let i=0;i<64&&current;i++){current=parents.get(current)||"";if(current===parent)return true;}return false;}
async function assignmentOrgAllowed(user:User,personOrg:string|null,targetOrg:string,accountId:string){if(!personOrg)return user.role==="super_admin"&&accountId===user.id;if(await orgDescendant(user,personOrg,targetOrg))return true;return canManage(user)&&await orgDescendant(user,targetOrg,personOrg);}
async function activeUsers(user:User,ids:string[]){const found:Record<string,any>[]=[];for(const id of [...new Set(ids)]){const rows=await db()`SELECT id,org_id,status FROM nexusflow.users WHERE id=${id} AND tenant_id IS NOT DISTINCT FROM ${user.tenant_id}`;if(!rows[0]||rows[0].status!=="active")throw new Error(`active same-tenant user required: ${id}`);found.push(rows[0]);}return found;}
export async function taskTargetOrganizations(user:User,task:Record<string,any>){const assignments=await db()`SELECT data FROM nexusflow.records WHERE kind='task_assignments' AND tenant_id IS NOT DISTINCT FROM ${user.tenant_id} AND data->>'task_id'=${String(task.id)} AND data->>'status' NOT IN ('cancelled','rejected')`;const ids=assignments.length?[...new Set(assignments.map((r:any)=>String(r.data.user_id)))]:[String(task.owner_id),...(Array.isArray(task.member_ids)?task.member_ids.map(String):[])],users=await activeUsers(user,ids),orgs=[...new Set(users.map(u=>String(u.org_id||"")).filter(Boolean))];return orgs.length?orgs:task.org_id?[String(task.org_id)]:[];}
export async function listRecords(user:User,kind:Collection):Promise<Array<Record<string,any>>> {
 const rows=await db()`SELECT id,tenant_id,created_by,data,created_at,updated_at FROM nexusflow.records WHERE kind=${kind} AND (${user.role==='super_admin'} OR tenant_id IS NOT DISTINCT FROM ${user.tenant_id}) ORDER BY created_at DESC`;
 const visible=[];for(const r of rows){const row={id:r.id,tenant_id:r.tenant_id,created_by:r.created_by,data:r.data as Record<string,unknown>};if(await canReadRecord(user,kind,row)){const data={...row.data};if(kind==="invitations")delete data.token_hash;visible.push({...data,id:r.id,created_at:r.created_at,updated_at:r.updated_at});}}return visible;
}
export async function getRecord(user:User,kind:Collection,id:string):Promise<Record<string,any>|null> {
 const rows=await db()`SELECT id,tenant_id,created_by,data,created_at,updated_at FROM nexusflow.records WHERE id=${id} AND kind=${kind} AND (${user.role==='super_admin'} OR tenant_id IS NOT DISTINCT FROM ${user.tenant_id})`;const r=rows[0];if(!r)return null;
 const row={id:r.id,tenant_id:r.tenant_id,created_by:r.created_by,data:r.data as Record<string,unknown>};if(!await canReadRecord(user,kind,row))return null;const data={...row.data};if(kind==="invitations")delete data.token_hash;return {...data,id:r.id,created_at:r.created_at,updated_at:r.updated_at};
}
export async function createRecord(user:User,kind:Collection,input:Record<string,unknown>) {
 if(kind==="orgs"&&["demo_seed","department_approver_id","center_approver_id"].some(k=>k in input))throw new Error("approval identity fields are managed by account roles");
 if("id" in input||"created_at" in input||"updated_at" in input)throw new Error("server-managed fields cannot be supplied");
 const parsed=schemas[kind]?.safeParse(input);if(parsed&&!parsed.success)throw new Error(parsed.error.issues.map(x=>`${x.path.join(".")}: ${x.message}`).join("; "));
 const data={...(parsed?.data||input)} as Record<string,unknown>;
 if(kind==="orgs"){if(data.parent_id&&!await orgExists(user,String(data.parent_id)))throw new Error("parent organization unavailable");if(data.parent_id===data.id)throw new Error("organization cannot parent itself");}
 if(kind==="people"){if(!await orgExists(user,String(data.org_id||"")))throw new Error("organization unavailable");if(data.user_id){const linked=await activeUsers(user,[String(data.user_id)]);if(linked[0]?.org_id!==data.org_id)throw new Error("person and account organization must match");}}
 if(kind==="projects"){if(!await orgExists(user,String(data.org_id||"")))throw new Error("organization unavailable");const assignees=await activeUsers(user,[String(data.owner_id),...(Array.isArray(data.member_ids)?data.member_ids.map(String):[])]);for(const assignee of assignees)if(!await assignmentOrgAllowed(user,assignee.org_id?String(assignee.org_id):null,String(data.org_id),String(assignee.id)))throw new Error("project members must belong to the project organization scope");if(user.org_id&&!['center_director','super_admin'].includes(user.role)&&!await orgDescendant(user,String(data.org_id),user.org_id))throw new Error("project organization is outside your scope");}
 if(kind==="tasks"){
  if(!await allowedTaskTypes(user).then(values=>values.includes(String(data.type))))throw new Error("task type is not enabled by published configuration");
  if(data.status!=="draft")throw new Error("new tasks must start in draft");
  const start=String(data.start_date||""),end=String(data.end_date||"");if(!validDate(start)||!validDate(end)||start>end||(Date.parse(`${end}T00:00:00Z`)-Date.parse(`${start}T00:00:00Z`))/86400000>3660)throw new Error("task dates must be ordered and no more than 10 years apart");
  if(typeof data.all_day!=="boolean")throw new Error("all_day must be boolean");
  const ids=[String(data.owner_id),...(Array.isArray(data.member_ids)?data.member_ids.map(String):[])],assignees=await activeUsers(user,ids);data.member_ids=[...new Set(Array.isArray(data.member_ids)?data.member_ids.map(String):[])];
  const owner=assignees.find(a=>a.id===data.owner_id);data.org_id=String(data.org_id||owner?.org_id||"");if(!owner?.org_id&&!(user.role==="super_admin"&&owner?.id===user.id&&data.org_id))throw new Error("task owner must have an organization");
  if(!await orgExists(user,String(data.org_id)))throw new Error("task organization unavailable");
  for(const person of assignees)if(!await assignmentOrgAllowed(user,person.org_id?String(person.org_id):null,String(data.org_id),String(person.id)))throw new Error("task assignments must belong to its organization scope");
  if(!canManage(user)&&user.role!=="project_lead"&&(data.owner_id!==user.id||(data.member_ids as string[]).some((id:string)=>id!==user.id)))throw new Error("members may assign only themselves");
  if(data.project_id){const parent=await getRecord(user,"projects",String(data.project_id));if(!parent||!await canProjectAction(user,String(data.project_id),"edit"))throw new Error("project edit permission required");if(!await orgDescendant(user,String(data.org_id),String(parent.org_id)))throw new Error("task organization must be within project organization");const projectMembers=Array.isArray(parent.member_ids)?parent.member_ids:[];if(assignees.some(a=>!projectMembers.includes(a.id))&&!canManage(user))throw new Error("task assignees must be project members");}
 }
 if(kind==="config"&&(!canManage(user)||data.status!=="draft"))throw new Error("forbidden: configuration drafts require an administrator");
 if(kind==="task_assignments"){if(data.status!=="assigned"||Number(data.progress||0)!==0||["result","reviewed_by","reviewed_at","submitted_at","confirmed_by","confirmed_at"].some(k=>k in data))throw new Error("new assignments must be unapproved with zero progress");const task=await getRecord(user,"tasks",String(data.task_id));if(!task)throw new Error("task unavailable");if(task.status!=="draft")throw new Error("assignments can only be changed while the task is a draft");if(!await canEditTask(user,task))throw new Error("forbidden: parent task edit permission required");const categories=["personal-report","overall-report","presentation","application-report","dataset","minutes"];if(!Array.isArray(data.deliverables)||data.deliverables.some((x:any)=>!categories.includes(String(x))))throw new Error("invalid assignment deliverable categories");data.deliverables=[...new Set(data.deliverables.map(String))];const target=await activeUsers(user,[String(data.user_id)]);if(!await assignmentOrgAllowed(user,target[0]?.org_id?String(target[0].org_id):null,String(task.org_id),String(data.user_id)))throw new Error("assignment user is outside task organization");if(String(data.start_date)<String(task.start_date)||String(data.end_date)>String(task.end_date)||String(data.start_date)>String(data.end_date))throw new Error("assignment dates must be within task dates");if(task.project_id&&!await canProjectAction(user,String(task.project_id),"edit"))throw new Error("forbidden: project edit permission required");}
 if(kind==="dispatch"){if(data.status!=="draft")throw new Error("new dispatches must start in draft");const task=await getRecord(user,"tasks",String(data.task_id));if(!task)throw new Error("task unavailable");if(task.status!=="draft")throw new Error("dispatch task must be a draft");if(data.workflow==="supplemental"){const origin=await db()`SELECT created_by FROM nexusflow.records WHERE id=${String(task.id)} AND kind='tasks' AND tenant_id IS NOT DISTINCT FROM ${user.tenant_id}`;if(!origin[0]||data.requester_id!==String(origin[0].created_by))throw new Error("supplemental requester must be the original task requester");if(user.id!==String(origin[0].created_by)&&user.id!==String(task.owner_id)&&!canManage(user))throw new Error("only the requester, task owner, or manager may prepare supplemental dispatch");}else if(data.requester_id!==user.id)throw new Error("dispatch requester must be the current user");const targets=await taskTargetOrganizations(user,task),requested=Array.isArray(data.target_org_ids)?[...new Set(data.target_org_ids.map(String))]:[];if(requested.length&&(requested.length!==targets.length||requested.some(org=>!targets.includes(org))))throw new Error("dispatch targets must exactly match actual assignee organizations");data.target_org_ids=targets;}
 if(kind==="visibility_grants"){const project=await getRecord(user,"projects",String(data.project_id));if(!project)throw new Error("project unavailable");for(const action of data.actions as Array<"view"|"edit">)if(!await canProjectAction(user,String(data.project_id),action))throw new Error("forbidden: cannot grant a project action you do not possess");if(!sql)throw new Error("DATABASE_URL required");const target=await activeUsers(user,[String(data.user_id)]);if(!target.length)throw new Error("grant target user unavailable");data.org_id=project.org_id;}
 const row={tenant_id:user.tenant_id,created_by:user.id,data};if(!await canWriteRecord(user,kind,row,"create"))throw new Error("forbidden");
 if(kind==="approvals"||kind==="inbox"||kind==="conflicts"||kind==="worklogs"||kind==="load"||kind==="seed"||kind==="config_versions"||kind==="mentions")throw new Error("records of this type are created by domain actions");
 if(kind==="orgs"&&!['super_admin','center_director'].includes(user.role))throw new Error("organization management permission required");
 const id=uuid();await db().begin(async tx=>{if(kind==="task_assignments"){const parent=await tx`SELECT data FROM nexusflow.records WHERE id=${String(data.task_id)} AND kind='tasks' AND tenant_id IS NOT DISTINCT FROM ${user.tenant_id} FOR UPDATE`;if(!parent[0]||(parent[0].data as any).status!=="draft"||!await canEditTask(user,{...(parent[0].data as any),id:String(data.task_id)}))throw new Error("forbidden: parent task is no longer editable");}if(kind==="dispatch"){const locked=await tx`SELECT data FROM nexusflow.records WHERE id=${String(data.task_id)} AND kind='tasks' AND tenant_id IS NOT DISTINCT FROM ${user.tenant_id} FOR UPDATE`;if(!locked[0]||(locked[0].data as any).status!=="draft")throw new Error("dispatch task is no longer a draft");const targets=await taskTargetOrganizations(user,{...(locked[0].data as any),id:String(data.task_id)});if(targets.length!==((data.target_org_ids as string[])||[]).length||targets.some(org=>!(data.target_org_ids as string[]).includes(org)))throw new Error("dispatch targets changed; recreate dispatch");}await tx`INSERT INTO nexusflow.records(id,kind,tenant_id,created_by,data) VALUES(${id},${kind},${user.tenant_id},${user.id},${tx.json(data as any)})`;if(kind==="tasks"){const assigned=[...new Set([String(data.owner_id),...(Array.isArray(data.member_ids)?data.member_ids.map(String):[])])];for(const user_id of assigned)await insertRecord(tx,user,"task_assignments",{task_id:id,user_id,start_date:data.start_date,end_date:data.end_date,daily_hours:data.daily_hours,all_day:data.all_day,status:"assigned",progress:0,deliverables:[]});}if(kind==="task_assignments"){const locked=await tx`SELECT data FROM nexusflow.records WHERE id=${String(data.task_id)} AND kind='tasks' AND tenant_id IS NOT DISTINCT FROM ${user.tenant_id} FOR UPDATE`;if(!locked[0])throw new Error("task unavailable");const task=locked[0].data as any;if(task.status!=="draft")throw new Error("assignments can only be changed while the task is a draft");if(!await canEditTask(user,{...task,id:String(data.task_id)}))throw new Error("forbidden: parent task edit permission required");const duplicate=await tx`SELECT id FROM nexusflow.records WHERE kind='task_assignments' AND tenant_id IS NOT DISTINCT FROM ${user.tenant_id} AND data->>'task_id'=${String(data.task_id)} AND data->>'user_id'=${String(data.user_id)} AND id<>${id} LIMIT 1`;if(duplicate.length)throw new Error("user already assigned to task");const members=[...new Set([...(Array.isArray(task.member_ids)?task.member_ids.map(String):[]),String(data.user_id)])];await tx`UPDATE nexusflow.records SET data=data||${tx.json({member_ids:members} as any)},updated_at=now() WHERE id=${String(data.task_id)} AND kind='tasks'`;};await tx`INSERT INTO nexusflow.audit(id,actor,tenant_id,action,object_kind,object_id,data) VALUES(${uuid()},${user.id},${user.tenant_id},${kind + ".create"},${kind},${id},${tx.json(data as any)})`;});return getRecord(user,kind,id);
}
export async function updateRecord(user:User,kind:Collection,id:string,patch:Record<string,unknown>) {
 if(kind==="orgs"&&["demo_seed","department_approver_id","center_approver_id"].some(k=>k in patch))throw new Error("approval identity fields are managed by account roles");
 if("id" in patch||"created_at" in patch||"updated_at" in patch||"created_by" in patch||"tenant_id" in patch)throw new Error("server-managed fields cannot be changed");
 if(kind==="task_assignments")throw new Error("use assignment workflow actions to update assignments");
 if(kind==="tasks"&&["status","owner_id","member_ids","project_id","org_id","start_date","end_date","daily_hours","all_day"].some(k=>k in patch))throw new Error("use a task workflow action to change lifecycle or assignment");
 if(kind==="config"&&"status" in patch)throw new Error("use config publish action to change activation state");
 if(kind==="invitations"||kind==="visibility_grants")throw new Error("use the dedicated revoke/grant action");
 if(kind==="people"&&["org_id","user_id","role"].some(k=>k in patch))throw new Error("account and organization binding requires an admin workflow");
 if(kind==="orgs"&&"parent_id" in patch)throw new Error("organization moves require an admin workflow");
 if(kind==="dispatch")throw new Error("use dispatch workflow actions to change dispatch records");if(kind==="approvals"&&["status","approver_id","step"].some(k=>k in patch))throw new Error("use approval actions to change workflow state");
 if(kind==="files"&&["status","object_key","size_bytes"].some(k=>k in patch))throw new Error("use the file archive or upload action");
 if(kind==="projects"&&"status" in patch)throw new Error("use project lifecycle action to change status");if(kind==="projects"&&["visibility","member_ids","owner_id"].some(k=>k in patch)&&!['super_admin','center_director','center_deputy','department_director'].includes(user.role))throw new Error("project administration permission required");
 const current=await getRaw(kind,id,user);if(!current)return null;if(!await canWriteRecord(user,kind,current,"update"))throw new Error("forbidden");
 const next={...current.data,...patch};if(kind==="config"&&current.data.status==="published"&&("value" in patch||"key" in patch))return createRecord(user,"config",{...next,status:"draft",version:Number(current.data.version||0)});if(kind==="config"&&current.data.status!=="draft")throw new Error("only configuration drafts can be edited");const validated=kind==="tasks"?{...next,status:"draft"}:kind==="projects"?{...next,status:"planning"}:kind==="config"?{...next,status:"draft"}:next;const parsed=schemas[kind]?.safeParse(validated);if(parsed&&!parsed.success)throw new Error(parsed.error.issues.map(x=>x.message).join("; "));
 if(kind==="projects"){if(!await orgExists(user,String(next.org_id||"")))throw new Error("project organization unavailable");const members=await activeUsers(user,[String(next.owner_id),...(Array.isArray(next.member_ids)?next.member_ids.map(String):[])]);for(const assignee of members)if(!await assignmentOrgAllowed(user,assignee.org_id?String(assignee.org_id):null,String(next.org_id),String(assignee.id)))throw new Error("project members must belong to the project organization scope");if(user.org_id&&!['center_director','super_admin'].includes(user.role)&&!await orgDescendant(user,String(next.org_id),user.org_id))throw new Error("project organization is outside your scope");}
 await db().begin(async tx=>{const locked=await tx`SELECT data,updated_at FROM nexusflow.records WHERE id=${id} AND kind=${kind} AND tenant_id IS NOT DISTINCT FROM ${current.tenant_id} FOR UPDATE`;if(!locked[0]||new Date(locked[0].updated_at).valueOf()!==new Date(current.updated_at).valueOf())throw new Error("record changed; retry the update");await tx`UPDATE nexusflow.records SET data=${tx.json(next as any)},updated_at=now() WHERE id=${id} AND kind=${kind} AND tenant_id IS NOT DISTINCT FROM ${current.tenant_id}`;await tx`INSERT INTO nexusflow.audit(id,actor,tenant_id,action,object_kind,object_id,data) VALUES(${uuid()},${user.id},${user.tenant_id},${kind + ".update"},${kind},${id},${tx.json({before:current.data,after:next} as any)})`;});return getRecord(user,kind,id);
}
async function getRaw(kind:Collection,id:string,user:User){const r=(await db()`SELECT id,tenant_id,created_by,data,updated_at FROM nexusflow.records WHERE id=${id} AND kind=${kind} AND (${user.role==='super_admin'} OR tenant_id IS NOT DISTINCT FROM ${user.tenant_id})`)[0];return r?{id:r.id,tenant_id:r.tenant_id,created_by:r.created_by,data:r.data as Record<string,unknown>,updated_at:r.updated_at}:null;}
export async function deleteRecord(user:User,kind:Collection,id:string){if(["files","tasks","task_assignments","projects","orgs","people","invitations","visibility_grants"].includes(kind))return false;const r=await getRaw(kind,id,user);if(!r||kind==="config"&&r.data.status!=="draft"||!await canWriteRecord(user,kind,r,"delete"))return false;const refs=kind==="dispatch"?await db()`SELECT 1 FROM nexusflow.records WHERE tenant_id IS NOT DISTINCT FROM ${user.tenant_id} AND (kind='approvals' AND data->>'dispatch_id'=${id} OR kind='inbox' AND data->>'source_id'=${id}) LIMIT 1`:kind==="approvals"?await db()`SELECT 1 FROM nexusflow.records WHERE kind='inbox' AND tenant_id IS NOT DISTINCT FROM ${user.tenant_id} AND data->>'source_id'=${id} LIMIT 1`:[];if(refs.length)return false;return db().begin(async tx=>{const deleted=kind==="config"?await tx`DELETE FROM nexusflow.records WHERE id=${id} AND kind=${kind} AND tenant_id IS NOT DISTINCT FROM ${user.tenant_id} AND data->>'status'='draft' RETURNING id`:await tx`DELETE FROM nexusflow.records WHERE id=${id} AND kind=${kind} AND tenant_id IS NOT DISTINCT FROM ${user.tenant_id} RETURNING id`;if(!deleted.length)return false;await tx`INSERT INTO nexusflow.audit(id,actor,tenant_id,action,object_kind,object_id,data) VALUES(${uuid()},${user.id},${user.tenant_id},${kind + ".delete"},${kind},${id},${tx.json(r.data as any)})`;return true;});}
export async function insertRecord(tx:any,user:User,kind:Collection|"storage_cleanup"|"role_delegations",data:Record<string,unknown>) {const id=uuid();await tx`INSERT INTO nexusflow.records(id,kind,tenant_id,created_by,data) VALUES(${id},${kind},${user.tenant_id},${user.id},${tx.json(data)})`;return id;}
